# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('ratio', models.FloatField()),
                ('category', models.IntegerField()),
                ('imgCount', models.IntegerField()),
                ('imgElement', models.TextField()),
                ('textCount', models.IntegerField()),
                ('textElement', models.TextField()),
                ('textAlignment', models.IntegerField()),
                ('dominantColor', models.CharField(max_length=255)),
                ('palette', models.TextField()),
                ('backgroundColor', models.CharField(max_length=100)),
                ('textColor', models.CharField(max_length=100)),
                ('backgroundCategory', models.IntegerField()),
            ],
        ),
    ]
